services:
  mongodb:
    container_name: mongodb
    platform: linux/arm64/v8
    image: mongo:7.0.16-jammy
    ports:
      - 27017:27017
    volumes:
      - .mongo-data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  hocuspocus:
    container_name: hocuspocus
    build:
      context: .
      dockerfile: Dockerfile
    image: hocuspocus-image
    pull_policy: build
    ports:
      - 8001:8001
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      mongodb:
        condition: service_healthy
        restart: true
